export const placeholders = {
    fr: {
        typography: {
            h1_context: "Giscardpunk",                                                                                                                                                                              
            h2_context: "Cyberpunk",                                                                                                                                                                                
            h3_context: "Steampunk",                                                                                                                                                                                
            h4_context: "Dieselpunk",                                                                                                                                                                               
            h5_context: "Solarpunk",       
            h6_context: "Juste punk",
            lead: "Adipisci velit sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.",
            body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            paragraph: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
        },
        badges: {
            accent: "Accent",
            tone: "Ton",
            delete: "Supprimer",
            warning: "Attention",
            confirm: "Confirmer",
            info: "Info",
            click_me: "Cliquez-moi",
            add: "Ajouter",
            see_more: "Voir plus",
            pending: "En attente",
            validated: "Validé",
            location: "Emplacement",
            see_map: "Voir la carte",
            link: "Lien",
            learn_more: "En savoir plus",
            filters: ["Design", "Svelte", "A11y"],
            filter_remove: "Retirer",
            all_removed: "Tous retirés",
            click: "click",
        },
        buttons: {
            large: "grand",
            medium: "moyen",
            small: "petit",
            uppercase: "majuscule",
            anim_left: "gauche",
            anim_right: "droite",
            anim_top: "haut",
            anim_bottom: "bas",
            text: "texte",
            accent: "Accent",
            tone: "Ton",
            delete: "Supprimer",
            warning: "Attention",
            confirm: "Confirmer",
            info: "Info",
            neutral: "Neutre",
            rect: "Rectangulaire",
            squared: "Carré",
        },
        form: {
            placeholder_name: "Ex. Johnny Matignon",
            placeholder_email: "punk@republique.fr",
            placeholder_message: "Merci d'avoir osé le futur"
        },
        navigation: {
            items: ["TGV", "Concorde", "Ariane", "Minitel"],
            label1: "TGV",
            label2: "Concorde",
            label3: "Ariane",
            label4: "Minitel",
            label5: "Contact"
        },
        alerts: {
            success: "La catalogue de la COGIP est bien arrivé dans votre boîte aux lettres",
            info: "Mettre un turboréacteur sur un train n'est pas économique",
            warning_pre: "Votre session expire bientôt.",
            warning_link: "Renouvelez votre abonnement Minitel maintenant",
            error: "Échec du lancement de la fusée Ariane"
        },
        callout: {
            success_label: "Succès",
            error_label: "Erreur",
            note_label: "Note",
            info: "Le réseau Minitel n'est fermée qu'en 2012 par France Télécom",
            success: "Le 26 février 1981 le TGV bat le record mondiale de vitesse sur rail avec 380 km/h",
            warning: "Votre facture téléphonique a dépassé 1000 francs",
            error:   "Échec du lancement de la fusée Ariane",
            accent:  "Astuce : vous pouvez composer librement les slots leading, children et following pour adapter le callout à votre usage.",
            neutral: "Ce composant est un message à caractère informatif et n'implique aucune action obligatoire de la part de l'utilisateur.",
            tip: "Composez librement <code>leading</code>, <code>children</code> et <code>following</code>. Le slot <code>leading</code> hérite de <code>--cb-color</code> automatiquement. Préférez <code>align='start'</code> pour du contenu multi-lignes — l'icône s'ancre en haut. Un <code>Button variant='ghost' palette='tone'</code> placé en <code>following</code> adopte la couleur du callout parent.",
            view: "Voir"
        },
        grid: {
            hero_text: "En vedette",
            tgv: {
                name: "TGV",
                origin: "France",
                years: "1981",
                abstract: "380 km/h les jours sans grève",
            },
            concord: {
                name: "Concorde",
                origin: "France & Royaume-Uni",
                years: "1976",
                abstract: "Supersonique, super-bruyant et super-chère",
            },
            minitel: {
                name: "Minitel",
                origin: "France",
                years: "1980",
                abstract: "3615 Internet",
            },
            ariane: {
                name: "Ariane 3",
                origin: "Europe",
                years: "1984",
                abstract: "Comment lancer Astérix dans l'espace",
            },
            renault: {
                name: "Renault Gabbiano Concept",
                origin: "France",
                years: "1983",
                abstract: "Ne viens pas du futur mais peut-être De Lorraine",
            },
            attribution: {
                header: "Photographies sous licence CC-BY-SA (3.0 et 4.0)",
                tgv: "TGV : joost.j bakker",
                tgv_link: "https://commons.wikimedia.org/w/index.php?curid=11305259",
                concord: "Concorde : Eduard Marmet",
                concord_link: "https://www.airliners.net/photo/British-Airways/Aerospatiale-BAC-Concorde-102/1406076/L",
                minitel: "Minitel : Bernard Marti",
                minitel_link: "https://commons.wikimedia.org/w/index.php?curid=15102738",
                ariane: "Ariane 3 : ESA/CNES/Arianespace",
                ariane_link: "https://www.esa.int/Enabling_Support/Space_Transportation/Ariane/40_years_of_Ariane",
                renault : "Renault Gabbiano : Renault/Italdesign",
                renault_link: ""
            }
        },
        selector: {
            sect_standalone: "Selector standalone — sans ControlBar, tokens de fallback",
            sect_tone: "ControlBar palette tone — fond card",
            sect_accent: "ControlBar palette accent — fond accent",
            sect_swatches: "Control Bar avec header — rounded — pastilles de couleur",
            sect_borderless: "ControlBar bordered={false} avec header — séparateur header uniquement",
            sect_interactive: "Démo interactive — contrôle les props du ControlBar/Selector ci-dessous",
            lbl_layout: "Disposition",
            lbl_cols: "Colonnes",
            lbl_rounded: "Coins",
            lbl_color: "Couleur",
            lbl_bar_visible: "Bar",
            lbl_bar_palette: "Bar palette",
            lbl_bar_bordered: "Bar bordered",
            lbl_bar_rounded: "Bar rounded",
            lbl_sel_palette: "Btn palette",
            lbl_sel_variant: "Btn variant",
            lbl_sel_size: "Btn size",
            lbl_sel_rounded: "Btn rounded",
            lbl_sel_uppercase: "Btn uppercase",
            opt_on: "true",
            opt_off: "false",
            selected_color: "Couleur sélectionnée :",
            header_borderless: "Paramètres d'affichage",
            header_interactive: "Résultat",
        },
        cards: {
            tiles: [
                {
                    name: "Catalogue COGIP",
                    description: "Retrouvez le meilleur de la GOGIP, préparé par nos chefs d'étages.",
                    badge: "Design",
                    btn: "Découvrir"
                },
                {
                    name: "3618 MIAMI",
                    description: "Pour contacter d'autres utilisateurs de Minitel",
                    badge: "Liberté",
                    btn: "PTT"
                },
                {
                    name: "Aérotrain",
                    description: "Image : Association des amis de Jean Bertin",
                    badge: "Ingénierie",
                    btn: "Source"
                }
            ],
            testimonials: [
                {
                    name: "Valéry G.E.",
                    role: "Cardiologue",
                    quote: "Vous n'avez pas le monopôle du coeur.",
                    avatar_initial: "VGE"
                },
                {
                    name: "Jacques C.",
                    role: "Agriculteur",
                    quote: "Mangez des pommes !",
                    avatar_initial: "JC"
                },
                {
                    name: "Jean-Pierre R.",
                    role: "Professeur d'anglais",
                    quote: "Win the yes needs the no, to win against the no !",
                    avatar_initial: "JR"
                }
            ],
            profile: {
                name: "Jean Michel",
                initials: "JM",
                role: "Designeur de jouet",
                bio: "Je conçois des jouets professionnels mais surtout rigolo en 220V pour vos bambins de 1 à 4 ans. Les jouets Jean-Michel c'est sensationnel.",
                langs: ["FR", "EN", "DE"],
                skills_label: "Compétences",
                skills: [
                    { value: "dessin", label: "dessin" },
                    { value: "gravure", label: "gravure" },
                    { value: "220V", label: "Haute Tension" },
                ],
                experience_label: "Expérience",
                experience: [
                    { date: "1980 – présent", role: "PDG · Jouets Jean-Michel" },
                    { date: "1975 – 1980", role: "Illustrateur · COGIP" },
                    { date: "1972 – 1975", role: "Graveur de Timbres · PTT" }
                ],
                contact_btn: "Secrétariat",
                cv_btn: "Recevoir notre catalogue par courrier",
                contact_email: "3615 MICHEL",
                linkedin_label: "LinkedIn"
            }
        },
        list_items: {
            nav: [
                { main: "TGV (tone)", extra: "Paris — Lyon" },
                { main: "Concorde (highlight)", extra: "Paris — New York" },
                { main: "Ariane (accent)", extra: "Kourou — Station spatial Mir" },
            ],
            delete_main:  "Annuler la mission (error)",
            delete_extra: "Action irréversible",
            warning_main:  "Mettre en attente (warning)",
            warning_extra: "Nécessite une validation",
            success_main:  "Mission accomplie (success)",
            success_extra: "Ariane est en orbite",
            info_main:  "Consulter les archives (info)",
            info_extra: "Dossier COGIP 1984",
        },
        switch_demo: {
            wifi: "Wi-Fi",
            notifications: "Notifications",
            light_mode: "Mode clair",
            dark_mode: "Mode sombre",
            airplane: "Mode avion",
            bluetooth: "Bluetooth",
            sync: "Synchronisation",
            dnd: "Ne pas déranger",
            eco: "Mode Éco"
        },
        input_demo: {
            title: "Input & Textarea",
            lbl_size: "Taille",
            sect_signup: "Créer un compte",
            sect_contact: "Envoyer un message",
            lbl_first_name: "Prénom",
            lbl_last_name: "Nom",
            lbl_email: "Email",
            lbl_password: "Mot de passe",
            lbl_pw_repeat: "Répéter le mot de passe",
            lbl_name: "Nom",
            lbl_subject: "Sujet",
            lbl_message: "Message",
            ph_first_name: "Jean",
            ph_last_name: "Dupont",
            ph_email: "vous@exemple.fr",
            ph_name: "Votre nom",
            ph_subject: "De quoi s'agit-il ?",
            ph_message: "Écrivez votre message ici…",
            hint_password: "Minimum 8 caractères",
            hint_message: "Minimum 20 caractères",
            success_pw: "Les mots de passe correspondent",
            error_pw: "Les mots de passe ne correspondent pas",
            error_msg_short: "Message trop court (min 20 caractères)",
            success_msg: "Parfait !",
            btn_signup: "Créer le compte",
            btn_send: "Envoyer",
            hint_email_ref: "Nous ne partagerons jamais votre adresse",
            error_ref: "Adresse email invalide",
            error_ref_ta: "Message trop court",
            success_ref: "Parfait !",
            too_short: "Trop court",
            long_enough: "Ce message est assez long et sera validé.",
            disabled: "Contenu désactivé",
        },
        radio_demo: {
            options: [
                { value: "tgv", label: "TGV" },
                { value: "concorde", label: "Concorde" },
                { value: "minitel", label: "Minitel" },
                { value: "ariane", label: "Ariane" },
            ],
        },
        checkbox_demo: {
            options: [
                { value: "tgv", label: "TGV" },
                { value: "concorde", label: "Concorde" },
                { value: "minitel", label: "Minitel" },
                { value: "ariane", label: "Ariane" },
            ],
        },
        search_field: {
            search_placeholder: "Rechercher un élément"
        },
        select_demo: {
            countries: [
                { value: "fr", label: "France" },
                { value: "de", label: "Allemagne" },
                { value: "es", label: "Espagne" },
                { value: "it", label: "Italie" },
                { value: "pt", label: "Portugal" },
                { value: "nl", label: "Pays-Bas" },
                { value: "be", label: "Belgique" },
                { value: "ch", label: "Suisse" },
                { value: "at", label: "Autriche" },
                { value: "se", label: "Suède" },
            ],
            languages: [
                { value: "js", label: "JavaScript" },
                { value: "ts", label: "TypeScript" },
                { value: "py", label: "Python" },
                { value: "rs", label: "Rust" },
                { value: "go", label: "Go" },
                { value: "rb", label: "Ruby" },
                { value: "java", label: "Java" },
                { value: "cs", label: "C#" },
                { value: "cpp", label: "C++" },
                { value: "swift", label: "Swift" },
                { value: "kt", label: "Kotlin" },
                { value: "php", label: "PHP" },
                { value: "svelte", label: "Svelte" },
            ],
            fruits: [
                { value: "apple", label: "Pomme" },
                { value: "banana", label: "Banane" },
                { value: "cherry", label: "Cerise" },
                { value: "grape", label: "Raisin" },
                { value: "mango", label: "Mangue" },
                { value: "orange", label: "Orange" },
                { value: "peach", label: "Pêche" },
                { value: "strawberry", label: "Fraise" },
            ],
            roles: [
                { value: "admin", label: "Administrateur" },
                { value: "editor", label: "Éditeur" },
                { value: "viewer", label: "Lecteur" },
                { value: "guest", label: "Invité" },
            ],
            statuses: [
                { value: "active", label: "Actif" },
                { value: "inactive", label: "Inactif" },
                { value: "suspended", label: "Suspendu" },
            ],
            lbl_country: "Pays",
            ph_country: "Choisissez un pays",
            hint_country: "Sélectionnez votre pays de résidence",
            lbl_language: "Langage",
            ph_language: "Choisissez un langage",
            search_language: "Filtrer les langages…",
            lbl_fruit: "Fruit",
            ph_fruit: "Choisissez un fruit",
            fruit_header: "Choisissez votre fruit préféré",
            fruit_clear: "Effacer la sélection",
            lbl_role: "Rôle",
            ph_role: "Sélectionnez un rôle",
            error_role: "Veuillez sélectionner un rôle",
            lbl_status: "Statut",
            ph_status: "Sélectionnez un statut",
            success_status: "Statut sélectionné",
            lbl_disabled: "Verrouillé",
            lbl_selected: "Sélectionné :",
            lbl_none: "aucun",
            hint_shipping: "Nous l'utiliserons pour la livraison",
            error_required: "Ce champ est obligatoire",
            success_selected: "Pays sélectionné",
            sect_basic: "Basique",
            sect_searchable: "Recherchable",
            sect_slots: "Slots header & footer",
            sect_validation: "États de validation",
            sect_states: "États du Select",
        },
        popover: {
            open: "Ouvrir",
            close: "Fermer",
            match: "S'étend pour atteindre la largeur de l'ancre",
            settings: "Options",
            profile: "Profil"
        },
        command: {
            groups: {
                file: "Fichier",
                edit: "Édition",
                view: "Affichage",
                engineering: "Ingénierie",
                design: "Design",
                product: "Produit",
                empty: "Pas de résultats"
            },
            items: {
                new_file: "Nouveau fichier",
                open_file: "Ouvrir un fichier",
                save: "Enregistrer",
                save_as: "Enregistrer sous…",
                undo: "Annuler",
                redo: "Rétablir",
                find: "Rechercher",
                replace: "Rechercher et remplacer",
                theme: "Changer de thème",
                drawer: "Afficher/masquer le tiroir",
                terminal: "Afficher/masquer le terminal",
                zoom_in: "Zoom avant",
                zoom_out: "Zoom arrière",
            },
            team: {
                alice: "Alice Martin",
                bob: "Bob Chen",
                carol: "Carol Dupont",
                david: "David Kim",
                eve: "Eve Santos",
                frank: "Frank Müller",
            },
            nav: {
                home: "Aller à l'accueil",
                settings: "Ouvrir les paramètres",
                profile: "Voir le profil",
                logout: "Se déconnecter",
                help: "Centre d'aide",
            },
            group_commands: "Groupe de commandes",
            open_cmd: "Ouvrir Command",
            custom_item: "Item personnalisé via Snippet",
            search_team: "Chercher un membre de l'équipe",
            no_groups: "Sans groupes",
            quick_nav: "Navigation rapide",
            placeholder_commands: "Entrez une commande…",
            placeholder_team: "Rechercher un membre…",
            placeholder_nav: "Où aller ?",
            empty: "Aucun résultat",
            selected_item: "Sélectionné :"
        },
        modal: {
            // Tone palette — delete confirmation
            tone_title: "Supprimer le fichier",
            tone_body: "Êtes-vous sûr de vouloir supprimer « tokens.css » ? Cette action est définitive et ne peut pas être annulée.",
            tone_confirm: "Supprimer",
            tone_cancel: "Annuler",
            // Accent palette — announcement
            accent_title: "Catalogue disponible",
            accent_body: "Le catalogue COGIP 1984 est disponible en téléchargement. 420 pages, index Minitel inclus.",
            accent_cta: "Télécharger",
            accent_dismiss: "Plus tard",
            // Composition — profile
            compose_name: "Jean Michel",
            compose_role: "Designeur de jouet",
            compose_bio: "Je conçois des jouets professionnels mais surtout rigolos en 220V pour vos bambins de 1 à 4 ans.",
            compose_skills: ["dessin", "220V", "gravure"],
            compose_contact: "Secrétariat",
            compose_close: "Fermer",
            // Width — narrow
            narrow_title: "Session expirée",
            narrow_body: "Votre session Minitel a expiré. Reconnectez-vous pour continuer.",
            narrow_confirm: "Reconnexion",
            narrow_cancel: "Annuler",
            // Width — wide
            wide_title: "Conditions d'utilisation du réseau Minitel",
            wide_body: "En accédant au réseau Minitel, vous acceptez les conditions générales d'utilisation établies par la Direction Générale des Télécommunications. L'utilisation des services 3615 est soumise à facturation à la minute. La COGIP décline toute responsabilité en cas de surtension électrique lors de la consultation du catalogue en ligne. Les données personnelles collectées seront conservées sur bande magnétique pendant une durée de 7 ans conformément à la réglementation en vigueur.",
            wide_accept: "J'accepte",
            wide_decline: "Je refuse",
        },
        accordion: {
            q1_label: "Qu'est-ce que ce design system ?",
            q1_body: "Une collection de composants Svelte 5 réutilisables construits avec un système de tokens. Chaque composant supporte la personnalisation par palette et par variante.",
            q2_label: "Comment personnaliser le thème ?",
            q2_body: "Utilisez la page de personnalisation pour ajuster les couleurs, polices et espacements. Tous les changements sont répercutés en temps réel via les propriétés CSS.",
            q3_label: "Quelles palettes sont disponibles ?",
            q3_body: "Le système fournit sept palettes sémantiques : accent, tone, neutral, error, warning, success et info. Chaque palette génère automatiquement des variantes hover, muted et background.",
            q4_label: "Élément désactivé",
            q4_body: "Ce contenu n'est pas accessible.",
        },
    },
    en: {
        typography: {
            h1_context: "Giscardpunk",
            h2_context: "Cyberpunk",
            h3_context: "Steampunk",
            h4_context: "Dieselpunk",
            h5_context: "Solarpunk",
            h6_context: "Just punk",
            lead: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis.",
            body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            paragraph: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
        },
        badges: {
            text: "text",
            accent: "Accent",
            tone: "Tone",
            delete: "Delete",
            warning: "Warning",
            confirm: "Confirm",
            info: "Info",
            click_me: "Click me",
            add: "Add",
            see_more: "See more",
            pending: "Pending",
            validated: "Validated",
            location: "Location",
            see_map: "See map",
            link: "Link",
            learn_more: "Learn more",
            filters: ["Design", "Svelte", "A11y"],
            filter_remove: "Remove",
            all_removed: "All removed",
            click: "click",
        },
        buttons: {
            large: "large",
            medium: "medium",
            small: "small",
            uppercase: "uppercase",
            anim_left: "left",
            anim_right: "right",
            anim_top: "up",
            anim_bottom: "down",
            text: "text",
            accent: "Accent",
            tone: "Tone",
            delete: "Delete",
            warning: "Warning",
            confirm: "Confirm",
            info: "Info",
            neutral: "Neutre",
            rect: "Rectangular",
            squared: "squared",
        },
        form: {
            placeholder_name: "Ex. Johnny Matignon",
            placeholder_email: "punk@republic.fr",
            placeholder_message: "Hey! Your design system is proper anarchy — clean as Téléphone, radical as a 1977 manifesto..."
        },
        navigation: {
            items: ["TGV", "Concorde", "Ariane", "Minitel"],
            label1: "TGV",
            label2: "Concorde",
            label3: "Ariane",
            label4: "Minitel",
            label5: "Contact"
        },
        alerts: {
            success: "The COGIP catalogue has been delivered to your mailbox",
            info: "Putting a turbojet engine on a train is not economical",
            warning_pre: "Your session will expire soon.",
            warning_link: "Renew your Minitel subscription now",
            error: "Failure to launch the Ariane rocket"
            },
        callout: {
            success_label: "Success",
            error_label: "Error",
            note_label: "Note",
            info: "The Minitel network was only closed in 2012 by France Télécom",
            success: "On 26 February 1981, the TGV broke the world rail speed record with 380 km/h",
            warning: "Your telephone bill has exceeded 1,000 francs",
            error:   "Failure of the Ariane rocket launch",
            accent:  "Tip: you can freely compose the leading, children and following slots to adapt the callout to your use.",
            neutral: "Note: this component is an informative message and does not imply any mandatory action on the part of the user.",
            tip: "Freely combine <code>leading</code>, <code>children</code>, and <code>following</code>. The <code>leading</code> slot automatically inherits <code>--cb-color</code>. Prefer <code>align='start'</code> for multi-line content — the icon anchors to the top. A <code>Button variant='ghost' palette='tone'</code> placed in <code>following</code> adopts the parent callout's color.",
            view: "View"
        },
        grid: {
            hero_text: "Featured",
            tgv: {
                name: "TGV",
                origin: "France",
                years: "1981",
                abstract: "380 km/h on non-strike days",
            },
            concord: {
                name: "Concorde",
                origin: "France & United Kingdom",
                years: "1976",
                abstract: "Supersonic, super-loud and super-expensive",
            },
            minitel: {
                name: "Minitel",
                origin: "France",
                years: "1980",
                abstract: "3615 Internet",
            },
            ariane: {
                name: "Ariane 3",
                origin: "Europe",
                years: "1984",
                abstract: "How to launch Astérix into space",
            },
            renault: {
                name: "Renault Gabbiano Concept",
                origin: "France",
                years: "1983",
                abstract: "Not from the future, but possibly from Lorraine",
            },
            attribution: {
                header: "Pictures under CC-BY-SA (3.0 and 4.0) license",
                tgv: "TGV : joost.j bakker",
                tgv_link: "https://commons.wikimedia.org/w/index.php?curid=11305259",
                concord: "Concord : Eduard Marmet",
                concord_link: "https://www.airliners.net/photo/British-Airways/Aerospatiale-BAC-Concorde-102/1406076/L",
                minitel: "Minitel : Bernard Marti",
                minitel_link: "https://commons.wikimedia.org/w/index.php?curid=15102738",
                ariane: "Ariane 3 : ESA/CNES/Arianespace",
                ariane_link: "https://www.esa.int/Enabling_Support/Space_Transportation/Ariane/40_years_of_Ariane",
                renault : "Renault Gabbiano : Renault/Italdesign",
                renault_link: ""
            }
        },
        selector: {
            sect_standalone: "Standalone Selector — no ControlBar, fallback tokens",
            sect_tone: "ControlBar palette tone — card background",
            sect_accent: "ControlBar palette accent — accent background",
            sect_swatches: "ControlBar with header — rounded — color dots",
            sect_borderless: "ControlBar bordered={false} with header — header separator only",
            sect_interactive: "Interactive demo — controls the ControlBar/Selector props below",
            lbl_layout: "Layout",
            lbl_cols: "Columns",
            lbl_rounded: "Corners",
            lbl_color: "Color",
            lbl_bar_visible: "Bar",
            lbl_bar_palette: "Bar palette",
            lbl_bar_bordered: "Bar bordered",
            lbl_bar_rounded: "Bar rounded",
            lbl_sel_palette: "Btn palette",
            lbl_sel_variant: "Btn variant",
            lbl_sel_size: "Btn size",
            lbl_sel_rounded: "Btn rounded",
            lbl_sel_uppercase: "Btn uppercase",
            opt_on: "on",
            opt_off: "off",
            selected_color: "Selected color:",
            header_borderless: "Display settings",
            header_interactive: "Result",
        },
        cards: {
            tiles: [
                {
                    name: "COGIP Catalogue",
                    description: "Discover the finest of COGIP, curated by our floor managers.",
                    badge: "Design",
                    btn: "Discover"
                },
                {
                    name: "3618 MIAMI",
                    description: "To get in touch with other Minitel users",
                    badge: "Freedom",
                    btn: "PTT"
                },
                {
                    name: "Aérotrain",
                    description: "Picture : Association des amis de Jean Bertin",
                    badge: "Engineering",
                    btn: "Source"
                }
            ],
            testimonials: [
                {
                    name: "Valéry G.E.",
                    role: "Cardiologist",
                    quote: "You don't have a monopoly on the heart.",
                    avatar_initial: "VGE"
                },
                {
                    name: "Jacques C.",
                    role: "Farmer",
                    quote: "Eat apples!",
                    avatar_initial: "JC"
                },
                {
                    name: "Jean-Pierre R.",
                    role: "English teacher",
                    quote: "Win the yes needs the no, to win against the no!",
                    avatar_initial: "JR"
                }
            ],
            profile: {
                name: "Jean Michel",
                initials: "JM",
                role: "Toy designer",
                bio: "I design professional yet fun 220V toys for your little ones aged 1 to 4. Jean-Michel toys are sensational.",
                langs: ["FR", "EN", "DE"],
                skills_label: "Skills",
                skills: [
                    { value: "dessin",  label: "drawing" },
                    { value: "gravure", label: "engraving" },
                    { value: "220V",    label: "High Voltage" },
                ],
                experience_label: "Experience",
                experience: [
                    { date: "1980 – present", role: "CEO · Jean-Michel Toys" },
                    { date: "1975 – 1980",    role: "Illustrator · COGIP" },
                    { date: "1972 – 1975",    role: "Stamp Engraver · PTT" }
                ],
                contact_btn: "Reception desk",
                cv_btn: "Receive our catalogue by post",
                contact_email: "3615 MICHEL",
                linkedin_label: "LinkedIn"
            }
        },
        list_items: {
            nav: [
                { main: "TGV (tone)", extra: "Paris — Lyon" },
                { main: "Concorde (highlight)", extra: "Paris — New York" },
                { main: "Ariane (accent)", extra: "Kourou — Mir space station" },
            ],
            delete_main:  "Cancel mission (error)",
            delete_extra: "Irreversible action",
            warning_main:  "Put on hold (warning)",
            warning_extra: "Requires validation",
            success_main:  "Mission accomplished (success)",
            success_extra: "Ariane is in orbit",
            info_main:  "Browse archives (info)",
            info_extra: "COGIP file 1984",
        },
        switch_demo: {
            wifi: "Wi-Fi",
            notifications: "Notifications",
            light_mode: "Light mode",
            dark_mode: "Dark mode",
            airplane: "Airplane mode",
            bluetooth: "Bluetooth",
            sync: "Sync",
            dnd: "Do not disturb",
            eco: "Eco mode"
        },
        input_demo: {
            sect_signup: "Create an account",
            sect_contact: "Send a message",
            lbl_first_name: "First name",
            lbl_last_name: "Last name",
            lbl_email: "Email",
            lbl_password: "Password",
            lbl_pw_repeat: "Repeat password",
            lbl_name: "Name",
            lbl_subject: "Subject",
            lbl_message: "Message",
            ph_first_name: "Jean",
            ph_last_name: "Dupont",
            ph_email: "you@example.com",
            ph_name: "Your name",
            ph_subject: "What is this about?",
            ph_message: "Write your message here…",
            hint_password: "Min 8 characters",
            hint_message: "Min 20 characters",
            success_pw: "Passwords match",
            error_pw: "Passwords do not match",
            error_msg_short: "Message too short (min 20 characters)",
            success_msg: "Looks good!",
            btn_signup: "Create account",
            btn_send: "Send",
            hint_email_ref: "We'll never share your email",
            error_ref: "Invalid email address",
            error_ref_ta: "Message too short",
            success_ref: "Looks good!",
            too_short: "Too short",
            long_enough: "This message is long enough to be valid and will pass validation.",
            disabled: "Disabled content",
        },
        radio_demo: {
            options: [
                { value: "tgv", label: "TGV" },
                { value: "concorde", label: "Concorde" },
                { value: "minitel", label: "Minitel" },
                { value: "ariane", label: "Ariane" },
            ],
        },
        checkbox_demo: {
            options: [
                { value: "tgv", label: "TGV" },
                { value: "concorde", label: "Concorde" },
                { value: "minitel", label: "Minitel" },
                { value: "ariane", label: "Ariane" },
            ],
        },
        search_field: {
            search_placeholder: "Search anything ..."
        },
        select_demo: {
            countries: [
                { value: "fr", label: "France" },
                { value: "de", label: "Germany" },
                { value: "es", label: "Spain" },
                { value: "it", label: "Italy" },
                { value: "pt", label: "Portugal" },
                { value: "nl", label: "Netherlands" },
                { value: "be", label: "Belgium" },
                { value: "ch", label: "Switzerland" },
                { value: "at", label: "Austria" },
                { value: "se", label: "Sweden" },
            ],
            languages: [
                { value: "js", label: "JavaScript" },
                { value: "ts", label: "TypeScript" },
                { value: "py", label: "Python" },
                { value: "rs", label: "Rust" },
                { value: "go", label: "Go" },
                { value: "rb", label: "Ruby" },
                { value: "java", label: "Java" },
                { value: "cs", label: "C#" },
                { value: "cpp", label: "C++" },
                { value: "swift", label: "Swift" },
                { value: "kt", label: "Kotlin" },
                { value: "php", label: "PHP" },
                { value: "svelte", label: "Svelte" },
            ],
            fruits: [
                { value: "apple", label: "Apple" },
                { value: "banana", label: "Banana" },
                { value: "cherry", label: "Cherry" },
                { value: "grape", label: "Grape" },
                { value: "mango", label: "Mango" },
                { value: "orange", label: "Orange" },
                { value: "peach", label: "Peach" },
                { value: "strawberry", label: "Strawberry" },
            ],
            roles: [
                { value: "admin", label: "Administrator" },
                { value: "editor", label: "Editor" },
                { value: "viewer", label: "Viewer" },
                { value: "guest", label: "Guest" },
            ],
            statuses: [
                { value: "active", label: "Active" },
                { value: "inactive", label: "Inactive" },
                { value: "suspended", label: "Suspended" },
            ],
            lbl_country: "Country",
            ph_country: "Choose a country",
            hint_country: "Select your country of residence",
            lbl_language: "Language",
            ph_language: "Pick a language",
            search_language: "Filter languages…",
            lbl_fruit: "Fruit",
            ph_fruit: "Pick a fruit",
            fruit_header: "Pick your favorite fruit",
            fruit_clear: "Clear selection",
            lbl_role: "Role",
            ph_role: "Select a role",
            error_role: "Please select a role",
            lbl_status: "Status",
            ph_status: "Select a status",
            success_status: "Status selected",
            lbl_disabled: "Locked",
            lbl_selected: "Selected:",
            lbl_none: "none",
            hint_shipping: "We'll use this for shipping",
            error_required: "This field is required",
            success_selected: "Country selected",
            sect_basic: "Basic",
            sect_searchable: "Searchable",
            sect_slots: "Header & Footer slots",
            sect_validation: "Validation states",
            sect_states: "Select states",
        },
        popover: {
            open: "Open",
            close: "Close",
            match: "Stretches to trigger width",
            settings: "Settings",
            profile: "Profile"
        },
        command: {
            groups: {
                file: "File",
                edit: "Edit",
                view: "View",
                engineering: "Engineering",
                design: "Design",
                product: "Product",
                empty: "No results"
            },
            items: {
                new_file: "New File",
                open_file: "Open File",
                save: "Save",
                save_as: "Save As…",
                undo: "Undo",
                redo: "Redo",
                find: "Find",
                replace: "Find and Replace",
                theme: "Toggle Theme",
                drawer: "Toggle Drawer",
                terminal: "Toggle Terminal",
                zoom_in: "Zoom In",
                zoom_out: "Zoom Out",
            },
            team: {
                alice: "Alice Martin",
                bob: "Bob Chen",
                carol: "Carol Dupont",
                david: "David Kim",
                eve: "Eve Santos",
                frank: "Frank Müller",
            },
            nav: {
                home: "Go to Home",
                settings: "Open Settings",
                profile: "View Profile",
                logout: "Log Out",
                help: "Help Center",
            },
            group_commands: "Grouped commands",
            open_cmd: "Open Command",
            custom_item: "Custom item snippet",
            search_team: "Search team",
            no_groups: "Without groups",
            quick_nav: "Quick navigation",
            placeholder_commands: "Type a command…",
            placeholder_team: "Search team members…",
            placeholder_nav: "Where to?",
            empty: "No results",
            selected_item: "Selected :"
        },
        modal: {
            tone_title: "Delete file",
            tone_body: "Are you sure you want to delete «tokens.css»? This action is permanent and cannot be undone.",
            tone_confirm: "Delete",
            tone_cancel: "Cancel",
            accent_title: "Catalogue available",
            accent_body: "The COGIP 1984 catalogue is now available for download. 420 pages, Minitel index included.",
            accent_cta: "Download",
            accent_dismiss: "Later",
            compose_name: "Jean Michel",
            compose_role: "Toy designer",
            compose_bio: "I design professional yet fun 220V toys for your little ones aged 1 to 4.",
            compose_skills: ["drawing", "220V", "engraving"],
            compose_contact: "Reception desk",
            compose_close: "Close",
            narrow_title: "Session expired",
            narrow_body: "Your Minitel session has expired. Please reconnect to continue.",
            narrow_confirm: "Reconnect",
            narrow_cancel: "Cancel",
            wide_title: "Minitel Network Terms of Use",
            wide_body: "By accessing the Minitel network, you agree to the general terms of use established by the Direction Générale des Télécommunications. Use of 3615 services is billed by the minute. COGIP accepts no liability for electrical surges during online catalogue browsing. Personal data collected will be stored on magnetic tape for 7 years in accordance with applicable regulations.",
            wide_accept: "I accept",
            wide_decline: "I decline",
        },
        accordion: {
            q1_label: "What is this design system?",
            q1_body: "A collection of reusable Svelte 5 components built with a token-based theming system. Every component supports palette and variant customization.",
            q2_label: "How do I customize the theme?",
            q2_body: "Use the customizer page to adjust colors, fonts, and spacing. All changes are reflected in real time through CSS custom properties.",
            q3_label: "Which palettes are available?",
            q3_body: "The system provides seven semantic palettes: accent, tone, neutral, error, warning, success, and info. Each palette generates hover, muted, and background variants automatically.",
            q4_label: "Disabled item",
            q4_body: "This content is not reachable.",
        },
    }
};

export type PlaceholdersType = typeof placeholders;
export type PlaceholderLocale = keyof PlaceholdersType;
